services:
  pixpro:
    build: .
    container_name: pixpro-pixpro-1
    environment:
      TZ: Asia/Taipei
    volumes:
      - .:/var/www/html
    ports:
      - "6767:80"
    restart: unless-stopped
